# Heart Disease

In [173]:
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,classification_report,accuracy_score

# EDA

In [174]:
# df=pd.read_csv('heart.csv')
# df.shape
# df['target'].value_counts().plot(kind='bar',color=['salmon','lightblue'])
# plt.show()
# df.info()
# df.isnull().sum()
# df.describe()
# df['sex'].value_counts()
# pd.crosstab(df.target,df.sex)
# pd.crosstab(df.target, df.sex).plot(kind="bar",figsize=(10,6),color=["salmon","lightblue"])  
# plt.title("Heart Disease Frerquency for Sex")  
# plt.xlabel("0 = No Disease, 1=Disease")  
# plt.ylabel("Amount")  
# plt.legend(["Female","Male"]);  
# plt.xticks(rotation=0);  
# plt.figure(figsize=(10,6))
# plt.scatter(df.age[df.target==1],df.thalach[df.target==1],c='salmon')
# plt.scatter(df.age[df.target==0],df.thalach[df.target==0],c='lightblue')
# plt.title('Heart Disease in function of age and max Heart Rate')
# plt.xlabel('Age')
# plt.ylabel('Max Heart Rate')
# plt.legend(['Disease','No Disease'])
# plt.show()
# df.age.plot.hist()
# plt.show()
# pd.crosstab(df.cp,df.target)
# pd.crosstab(df.cp,df.target).plot(kind='bar',figsize=(10,6),color=['salmon','lightblue'])
# plt.title('Heart Disease Frequency Per Chest Pain Type')
# plt.xlabel('Chest Pain Type')
# plt.ylabel('Amount')
# plt.legend(['No Disease','Disease'])
# plt.xticks(rotation=0)
# plt.show()
# df.corr()
# corr_matrix=df.corr()
# fig,ax=plt.subplots(figsize=(15,10))
# ax=sns.heatmap(corr_matrix,annot=True,linewidths=0.5,fmt='.2f',cmap='YlGnBu')
# bottom,top=ax.get_ylim()
# ax.set_ylim(bottom + 0.5, top-0.5)

In [175]:
df=pd.read_csv('heart.csv')
df.drop(['sex','exang','oldpeak','slope','ca','thal'],axis=1,inplace=True)
df.rename(columns={'cp':'chest_pain','trestbps':'blood_pressure','chol':'cholesterol','fbs':'fasting_blood_sugar','restecg':'ecg','thalach':'max_heart_rate'},inplace=True)
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [176]:
# # KNN
# model=KNeighborsClassifier()
# model.fit(X_train,y_train)
# print('Training Score:-',model.score(X_train,y_train))
# print('Testing Score:-',model.score(X_test,y_test))
# Training Score:- 0.8577405857740585
# Testing Score:- 0.711038961038961

# # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# # Decision Tree Classifier
# model=DecisionTreeClassifier(random_state=1,max_depth=10)
# model.fit(X_train,y_train)
# print('Training Score:-',model.score(X_train,y_train))
# print('Testing Score:-',model.score(X_test,y_test))
# Training Score:- 0.9846582984658299
# Testing Score:- 0.935064935064935

# # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# # Random Forest Classifier
# model=RandomForestClassifier(random_state=1,max_depth=7)
# model.fit(X_train,y_train)
# print('Training Score:-',model.score(X_train,y_train))
# print('Testing Score:-',model.score(X_test,y_test))
# Training Score:- 0.9860529986052998
# Testing Score:- 0.9318181818181818

# # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# # Logistic Regression
# model=LogisticRegression(random_state=1,solver='liblinear',max_iter=200)
# model.fit(X_train,y_train)
# print('Training Score:-',model.score(X_train,y_train))
# print('Testing Score:-',model.score(X_test,y_test))
# Training Score:- 0.7573221757322176
# Testing Score:- 0.737012987012987

# # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# # SVM
# model=SVC(random_state=1)
# model.fit(X_train,y_train)
# print('Training Score:-',model.score(X_train,y_train))
# print('Testing Score:-',model.score(X_test,y_test))
# Training Score:- 0.705718270571827
# Testing Score:- 0.6688311688311688

# # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [177]:
# Random Forest Classifier
model=RandomForestClassifier(random_state=1,max_depth=7)
model.fit(X_train,y_train)
print('Training Score:-',model.score(X_train,y_train))
print('Testing Score:-',model.score(X_test,y_test))

Training Score:- 0.9860529986052998
Testing Score:- 0.9318181818181818


In [178]:
pre=model.predict(X_test)
print('Accuracy Score:-\n',accuracy_score(y_test,pre))
print('-------------------------------------------------------------------------')
print('Confusion Matrix:-\n',confusion_matrix(y_test,pre))
print('-------------------------------------------------------------------------')
print('Precision Score:-',precision_score(y_test,pre))
print('-------------------------------------------------------------------------')
print('Recall Score:-',recall_score(y_test,pre))
print('-------------------------------------------------------------------------')
print('F1 Score:-',f1_score(y_test,pre))
print('-------------------------------------------------------------------------')
print('Classification Report:-\n',classification_report(y_test,pre))
print('-------------------------------------------------------------------------')

Accuracy Score:-
 0.9318181818181818
-------------------------------------------------------------------------
Confusion Matrix:-
 [[150  11]
 [ 10 137]]
-------------------------------------------------------------------------
Precision Score:- 0.9256756756756757
-------------------------------------------------------------------------
Recall Score:- 0.9319727891156463
-------------------------------------------------------------------------
F1 Score:- 0.9288135593220339
-------------------------------------------------------------------------
Classification Report:-
               precision    recall  f1-score   support

           0       0.94      0.93      0.93       161
           1       0.93      0.93      0.93       147

    accuracy                           0.93       308
   macro avg       0.93      0.93      0.93       308
weighted avg       0.93      0.93      0.93       308

-------------------------------------------------------------------------


In [179]:
pre1=model.predict(X_train)
print('Accuracy Score:-',accuracy_score(y_train,pre1))
print('-------------------------------------------------------------------------')
print('Confusion Matrix:-\n',confusion_matrix(y_train,pre1))
print('-------------------------------------------------------------------------')
print('Precision Score:-',precision_score(y_train,pre1))
print('-------------------------------------------------------------------------')
print('Recall Score:-',recall_score(y_train,pre1))
print('-------------------------------------------------------------------------')
print('F1 Score:-',f1_score(y_train,pre1))
print('-------------------------------------------------------------------------')
print('Classification Report:-\n',classification_report(y_train,pre1))
print('-------------------------------------------------------------------------')

Accuracy Score:- 0.9860529986052998
-------------------------------------------------------------------------
Confusion Matrix:-
 [[334   4]
 [  6 373]]
-------------------------------------------------------------------------
Precision Score:- 0.9893899204244032
-------------------------------------------------------------------------
Recall Score:- 0.9841688654353562
-------------------------------------------------------------------------
F1 Score:- 0.9867724867724867
-------------------------------------------------------------------------
Classification Report:-
               precision    recall  f1-score   support

           0       0.98      0.99      0.99       338
           1       0.99      0.98      0.99       379

    accuracy                           0.99       717
   macro avg       0.99      0.99      0.99       717
weighted avg       0.99      0.99      0.99       717

-------------------------------------------------------------------------


In [181]:
input=[[60,0,117,230,1,1,160]]
model.predict(input)

array([0], dtype=int64)

In [182]:
joblib.dump(model,'model.pkl')

['model.pkl']

In [186]:
df2=df.to_csv('test.csv')

In [185]:
df.columns

Index(['age', 'chest_pain', 'blood_pressure', 'cholesterol',
       'fasting_blood_sugar', 'ecg', 'max_heart_rate', 'target'],
      dtype='object')

In [187]:
df.describe()

age   chest_pain  blood_pressure  cholesterol  \
count  1025.000000  1025.000000     1025.000000   1025.00000   
mean     54.434146     0.942439      131.611707    246.00000   
std       9.072290     1.029641       17.516718     51.59251   
min      29.000000     0.000000       94.000000    126.00000   
25%      48.000000     0.000000      120.000000    211.00000   
50%      56.000000     1.000000      130.000000    240.00000   
75%      61.000000     2.000000      140.000000    275.00000   
max      77.000000     3.000000      200.000000    564.00000   

       fasting_blood_sugar          ecg  max_heart_rate       target  
count          1025.000000  1025.000000     1025.000000  1025.000000  
mean              0.149268     0.529756      149.114146     0.513171  
std               0.356527     0.527878       23.005724     0.500070  
min               0.000000     0.000000       71.000000     0.000000  
25%               0.000000     0.000000      132.000000     0.000000  
50%               0.000000     1.000000      152.000000     1.000000  
75%               0.000000     1.000000      166.000000     1.000000  
max               1.000000     2.000000      202.000000     1.000000